# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 100c25e08def96d51f085061420469992bd987810ee3c2f35893dda801cb84fbab3ae5009bf82447e58d63c765959d54dfe83fff72c2db501989568c102fa32e

test:
  secret_key_base: 292dffda7eb19b9b6348aeb1cbea413d76d49511dd36e02421aa691f459e80d567d1979c71dcf34e7a5971ea9e6082a6beb337534412d584c66191909d4c0076

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
